export const METADATA = {
  title: "One Year Anniversary",
  description:
    "",
  siteUrl: "",
};

export const MENULINKS = [
  {
    name: "Home",
    ref: "home",
  },
  {
    name: "Gallery",
    ref: "works",
  },
  {
    name: "Countdown",
    ref: "skills",
  },
  {
    name: "Timeline",
    ref: "timeline",
  },
];

export const TYPED_STRINGS = [
  "Sorry for my mistakes this year",
  "I'll strive to make you happier",
  "Missing our moments together",
  "Always by your side, always there"
];

export const EMOJI_LINKS = {
  linkedin: "🐷",
  github: "🐼",
  medium: "👸",
  instagram: "🤍",
  instagra: "💙",
};


export enum Branch {
  LEFT = "leftSide",
  RIGHT = "rightSide",
}

export enum NodeTypes {
  CONVERGE = "converge",
  DIVERGE = "diverge",
  CHECKPOINT = "checkpoint",
}

export enum ItemSize {
  SMALL = "small",
  LARGE = "large",
}

export const TIMELINE: Array<TimelineNodeV2> = [
  {
    type: NodeTypes.CHECKPOINT,
    title: "Starter",
    size: ItemSize.LARGE,
    subtitle:"",
    slideImage: "/MINE/Starter.png",
    shouldDrawLine: true,
    alignment: Branch.LEFT,
  },
  {
    type: NodeTypes.DIVERGE,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "First Bag",
    size: ItemSize.LARGE,
    subtitle: "This is the first gift that I brought for you. I wanted to make it a surprise, but you knew because you saw my bank account, haha.",
    slideImage: "/MINE/1st_bag(1).png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "First Final Exam Together",
    size: ItemSize.LARGE,
    subtitle: "This is our first final exam together! We're at Starbucks at The Paseo Park Kanchanapisek.",
    slideImage: "/MINE/1final.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "First Trip",
    size: ItemSize.LARGE,
    subtitle: "This is our first short trip together. We initially planned to go to Bang Saen but decided to go further, ending up in Pattaya.",
    slideImage: "/MINE/1st_trip.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {

    type: NodeTypes.CHECKPOINT,
    title: "First Film Photo",
    size: ItemSize.LARGE,
    subtitle: "This is our first film photo taken in Pattaya!",
    slideImage: "/MINE/film.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {

    type: NodeTypes.CHECKPOINT,
    title: "First M's birthday",
    size: ItemSize.LARGE,
    subtitle: "This is the first time we celebrated a birthday together.",
    slideImage: "/MINE/MBD.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "First Visit to M's Home",
    size: ItemSize.LARGE,
    subtitle: "This is the first time you came to my home, Love.",
    slideImage: "/MINE/Mhome.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {

    type: NodeTypes.CHECKPOINT,
    title: "Be My Girlfriend",
    size: ItemSize.LARGE,
    subtitle: "This is the necklace I gave you on Christmas Eve, the day you asked me to be your boyfriend. Thank you for making me happy since then.",
    slideImage: "/MINE/BeGF.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {

    type: NodeTypes.CHECKPOINT,
    title: "First Time with FIFA Friends",
    size: ItemSize.LARGE,
    subtitle: "That day we went to Traffic Bar at KU to drink with your friends for the first time, and it was fun.",
    slideImage: "/MINE/ff.jpg",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {

    type: NodeTypes.CHECKPOINT,
    title: "Second Trip",
    size: ItemSize.LARGE,
    subtitle: "After that, we took a bus to Pattaya and then a boat to Ko Lan.",
    slideImage: "/MINE/2trip.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {

    type: NodeTypes.CHECKPOINT,
    title: "Happy New Year",
    size: ItemSize.LARGE,
    subtitle: "On 31/12/2022, we went on a sidetrip around Bangkok to celebrate the New Year together, ending with dinner at Suki Dara with my friends.",
    slideImage: "/MINE/hpy.jpg",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {

    type: NodeTypes.CHECKPOINT,
    title: "New Hair Color V1",
    size: ItemSize.LARGE,
    subtitle: "This was your new hair color after the New Year, but you were unhappy with it, so I took you to get a new one.",
    slideImage: "/MINE/hairv1.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "First LEGO",
    size: ItemSize.LARGE,
    subtitle: "This is our first LEGO model together.",
    slideImage: "/MINE/LEGO.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CONVERGE,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "1 months",
    size: ItemSize.LARGE,
    subtitle: "",
    slideImage: "/MINE/Fv2.png",
    shouldDrawLine: true,
    alignment: Branch.LEFT,
  },
  {
    type: NodeTypes.DIVERGE,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "New Hair Color V2",
    size: ItemSize.LARGE,
    subtitle: "This is your new hair color. You look so happy and beautiful.",
    slideImage: "/MINE/hv2.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "Second LEGO",
    size: ItemSize.LARGE,
    subtitle: "This is our second LEGO model together.",
    slideImage: "/MINE/LEGO2.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "Valentine Day ",
    size: ItemSize.LARGE,
    subtitle: "On Valentine's Day, I took you to Audrey Cafe for an All-You-Can-Eat treat.",
    slideImage: "/MINE/V.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CONVERGE,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "2 months",
    size: ItemSize.LARGE,
    subtitle: "",
    slideImage: "/MINE/2m.png",
    shouldDrawLine: true,
    alignment: Branch.LEFT,
  },
  {
    type: NodeTypes.DIVERGE,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "First Midterm Exam together",
    size: ItemSize.LARGE,
    subtitle: "This is the end of the midterm exam day that we celebrate at the all-you-can-eat restaurant.",
    slideImage: "/MINE/1mid.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "Somewhere",
    size: ItemSize.LARGE,
    subtitle: "We drove somewhere, but I think it's the clinic, and you look so cute",
    slideImage: "/MINE/sw.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CONVERGE,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "3 months",
    size: ItemSize.LARGE,
    subtitle: "",
    slideImage: "/MINE/3m.png",
    shouldDrawLine: true,
    alignment: Branch.LEFT,
  },
  {
    type: NodeTypes.DIVERGE,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "Pre Bithday Fifa's Gift",
    size: ItemSize.LARGE,
    subtitle: "That day, I was determined to have you accept my offer to buy you new shoes. You said they were expensive, but finally, you accepted, and now we have matching shoes.",
    slideImage: "/MINE/BDG.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "Fifa Bithday Cake",
    size: ItemSize.LARGE,
    subtitle: "One day, we and our friends went to a shabu restaurant, and I tried to keep the cake a surprise, but failed. The funniest part was the deliveryman calling me about the cake's arrival while I was in the car with you, haha.",
    slideImage: "/MINE/FCAKE.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "Birthday Fifa",
    size: ItemSize.LARGE,
    subtitle: "This was your birthday where we and your friends celebrated three birthdays in one day at Rim Rooftop. You looked like a gorgeous princess that day.",
    slideImage: "/MINE/fBD.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CONVERGE,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "4 months",
    size: ItemSize.LARGE,
    subtitle: "",
    slideImage: "/MINE/4m.jpg",
    shouldDrawLine: true,
    alignment: Branch.LEFT,
  },
  {
    type: NodeTypes.DIVERGE,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "Congratulations",
    size: ItemSize.LARGE,
    subtitle: "Congratulations to you for your internship at National Central University, Taiwan.",
    slideImage: "/MINE/Taiwan.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "Frist Photo Booths",
    size: ItemSize.LARGE,
    subtitle: "This is our first photo booth at Central Westgate before I flew to Japan for an internship.",
    slideImage: "/MINE/1pb.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "You and My family",
    size: ItemSize.LARGE,
    subtitle: "You and my family at the airport before I went to the terminal.",
    slideImage: "/MINE/fam.jpg",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "No see for 2 months T_T",
    size: ItemSize.LARGE,
    subtitle: "This was our last video together for 2 months; that moment was super sad.",
    slideImage: "/MINE/air.jpg",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CONVERGE,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "5 Months",
    size: ItemSize.LARGE,
    subtitle: "",
    slideImage: "/MINE/5m.png",
    shouldDrawLine: true,
    alignment: Branch.LEFT,
  },
  {
    type: NodeTypes.DIVERGE,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "FIFA Prepares for Taiwan!",
    size: ItemSize.LARGE,
    subtitle: "This is the photo from the day you were to fly to Taiwan. You took a shower at around 2 AM to prepare to sleep, but then your mom woke you up at 3 AM, and you didn't sleep at all that day. In the end, you took two showers within 1-2 hours!",
    slideImage: "/MINE/PFT.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "FIFA Heads to Taiwan!",
    size: ItemSize.LARGE,
    subtitle: "This is the photo before you went to the terminal, with our boy Mac.",
    slideImage: "/MINE/FTaiwan.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "Taiwan Dorm",
    size: ItemSize.LARGE,
    subtitle: "This is the selfie you took for me at the Taiwan dorm.",
    slideImage: "/MINE/FTD.jpg",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "🤍",
    size: ItemSize.LARGE,
    subtitle: "This is the photo you took after your sidetrip in the town. It was raining a little, and you mentioned, 'Taiwan people looked at you as if they'd never seen anything like it before.' I apologize for the harsh words I spoke to you.",
    slideImage: "/MINE/LOVE.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CONVERGE,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "6 Months",
    size: ItemSize.LARGE,
    subtitle: "",
    slideImage: "/MINE/6m.png",
    shouldDrawLine: true,
    alignment: Branch.LEFT,
  },
  {
    type: NodeTypes.DIVERGE,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "🤍🤍",
    size: ItemSize.LARGE,
    subtitle: "",
    slideImage: "/MINE/LOVELOVE.jpg",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "🤍🤍🤍",
    size: ItemSize.LARGE,
    subtitle: "",
    slideImage: "/MINE/LOVELOVELOVE.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "😽",
    size: ItemSize.LARGE,
    subtitle: "",
    slideImage: "/MINE/vbvb.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "🐷",
    size: ItemSize.LARGE,
    subtitle: "",
    slideImage: "/MINE/twt.jpg",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "M Arrives in Taiwan!",
    size: ItemSize.LARGE,
    subtitle: "This is our first Instagram story after being apart for two months. That moment was super happy, getting to see you and hug you again.",
    slideImage: "/MINE/Mtw.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CONVERGE,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "7 months",
    size: ItemSize.LARGE,
    subtitle: "",
    slideImage: "/MINE/7m.png",
    shouldDrawLine: true,
    alignment: Branch.LEFT,
  },
  {
    type: NodeTypes.DIVERGE,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "M Returns to Thailand",
    size: ItemSize.LARGE,
    subtitle: "This is the last video of our Taiwan trip, taken when I flew to see you after finishing my internship in Japan.",
    slideImage: "/MINE/mgh.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "Our Boy Grows Up",
    size: ItemSize.LARGE,
    subtitle: "This is our boy, MAC, haha.",
    slideImage: "/MINE/ppc.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "Welcome Back Home",
    size: ItemSize.LARGE,
    subtitle: "This is the day I drove to Suvarnabhumi Airport to welcome you back home and drove you to your house.",
    slideImage: "/MINE/fgh.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "Something ...",
    size: ItemSize.LARGE,
    subtitle: "Something???, but this is the video from when we returned to our university.",
    slideImage: "/MINE/something.jpg",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "Something about 🐟?",
    size: ItemSize.LARGE,
    subtitle: "🍣🍣🍣🍣",
    slideImage: "/MINE/sal.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "Indiana Jones with you haha",
    size: ItemSize.LARGE,
    subtitle: "You and I watched all the Indiana Jones movies, haha.",
    slideImage: "/MINE/india.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CONVERGE,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "8 months",
    size: ItemSize.LARGE,
    subtitle: "",
    slideImage: "/MINE/8m.png",
    shouldDrawLine: true,
    alignment: Branch.LEFT,
  },
  {
    type: NodeTypes.DIVERGE,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "Sec Girl Thailand Workshop with You!",
    size: ItemSize.LARGE,
    subtitle: "These are the photos the cameraman took of you at the Sec Girl Thailand workshop. Your hair looked good. Thank you for coming to this event with me.",
    slideImage: "/MINE/sec.jpg",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "Brownie🍪",
    size: ItemSize.LARGE,
    subtitle: "This is the brownie with milk that you said you'd bring me to eat about 5-6 months ago, and I've waited almost a year.",
    slideImage: "/MINE/brownie.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "One ?!?",
    size: ItemSize.LARGE,
    subtitle: "Some photos where you're showing off your new nail color, but you look funny and cute, haha.",
    slideImage: "/MINE/one.jpg",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "Maid ?",
    size: ItemSize.LARGE,
    subtitle: "????",
    slideImage: "/MINE/maid.jpg",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "Shinkanzen",
    size: ItemSize.LARGE,
    subtitle: "This is our selfie from the group outing to eat at the Shinkansen buffet.",
    slideImage: "/MINE/shinkanzen.jpg",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "Cute 🐷",
    size: ItemSize.LARGE,
    subtitle: "",
    slideImage: "/MINE/cute.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },{
    type: NodeTypes.CHECKPOINT,
    title: "Second Photo Booth",
    size: ItemSize.LARGE,
    subtitle: "I love this one",
    slideImage: "/MINE/2pb2.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "You at Low Code",
    size: ItemSize.LARGE,
    subtitle: "This is the video interview that the Low Code event filmed you in.",
    slideImage: "/MINE/low.jpg",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CONVERGE,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "9 months",
    size: ItemSize.LARGE,
    subtitle: "",
    slideImage: "/MINE/9m.jpg",
    shouldDrawLine: true,
    alignment: Branch.LEFT,
  },
  {
    type: NodeTypes.DIVERGE,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "Din Tai Fung",
    size: ItemSize.LARGE,
    subtitle: "When we were in Taiwan, you tried to take me to a restaurant you assumed was Din Tai Fung, but it wasn't! That's why you need to take me to eat at Din Tai Fung here in Thailand, haha.",
    slideImage: "/MINE/din.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "At Milk Room?",
    size: ItemSize.LARGE,
    subtitle: "I brought dessert for you and your friends, and I took all of you to meet my mom, who agreed the dessert was GOOD.",
    slideImage: "/MINE/room.jpg",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "Funny thing together",
    size: ItemSize.LARGE,
    subtitle: "This is a screenshot from a your funny clip.",
    slideImage: "/MINE/fun.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "Police Wife???",
    size: ItemSize.LARGE,
    subtitle: "You took a photo at Best's house, and her father is a police officer, but does this look like a police wife???",
    slideImage: "/MINE/555.jpg",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CONVERGE,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "10 months",
    size: ItemSize.LARGE,
    subtitle: "",
    slideImage: "/MINE/10m.png",
    shouldDrawLine: true,
    alignment: Branch.LEFT,
  },
  {
    type: NodeTypes.DIVERGE,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "M's Second Birthday",
    size: ItemSize.LARGE,
    subtitle: "This is the second time celebrating my birthday that you surprised me. I came back after a conference in Chiang Mai.",
    slideImage: "/MINE/m2bd.jpg",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "uhhhh....",
    size: ItemSize.LARGE,
    subtitle: "....",
    slideImage: "/MINE/uhhh.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "Cute 2",
    size: ItemSize.LARGE,
    subtitle: "",
    slideImage: "/MINE/cute2.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "My babe",
    size: ItemSize.LARGE,
    subtitle: "",
    slideImage: "/MINE/babe.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "Airplane together",
    size: ItemSize.LARGE,
    subtitle: "This is our first time flying together, and your second time flying.",
    slideImage: "/MINE/airto.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "Choui Fong Tea",
    size: ItemSize.LARGE,
    subtitle: "After we arrived in Chiang Rai, I rented a car, and we went to the Choui Fong Tea field. This is our third trip.",
    slideImage: "/MINE/TEA.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "Mae Fah Luang University",
    size: ItemSize.LARGE,
    subtitle: "This is the day you presented at the conference at Mae Fah Luang University. You looked super gorgeous and professional; I love this look.",
    slideImage: "/MINE/MAE.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CONVERGE,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "11 months",
    size: ItemSize.LARGE,
    subtitle: "",
    slideImage: "/MINE/11m.png",
    shouldDrawLine: true,
    alignment: Branch.LEFT,
  },
  {
    type: NodeTypes.DIVERGE,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "Proposal Day",
    size: ItemSize.LARGE,
    subtitle: "This is our selfie before Proposal Day. It's cute, and you looked fantastic with your presentation.",
    slideImage: "/MINE/PDD.jpg",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "Our Art",
    size: ItemSize.LARGE,
    subtitle: "I challenged you to color a drawing book online and asked people on Instagram which one looked better. You lost, haha!",
    slideImage: "/MINE/art.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "Us and Friends at Night Market",
    size: ItemSize.LARGE,
    subtitle: "Our night at the Phra Pathom Chedi market.",
    slideImage: "/MINE/NM.png",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "Pattaya",
    size: ItemSize.LARGE,
    subtitle: "This is our fourth trip together, back to Pattaya  again but this time with friends! The next trip is waiting for us at Khao Yai National Park from 26/12 to 28/12 2023.",
    slideImage: "/MINE/aya.jpg",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "Nijungle's House",
    size: ItemSize.LARGE,
    subtitle: "After returning from our Pattaya trip, we went to Nijungle's house for a party.",
    slideImage: "/MINE/ni.jpg",
    shouldDrawLine: true,
    alignment: Branch.RIGHT,
  },
  {
    type: NodeTypes.CONVERGE,
  },
  {
    type: NodeTypes.CHECKPOINT,
    title: "1 Year",
    size: ItemSize.LARGE,
    subtitle: "I want to say thank you for being my girlfriend. I will improve myself for everything I've mistaken and I'm very happy to have you in my life. I will stay with you everywhere and every time. I'm always with you. Love you and looking forward to our next anniversary. I will always support you, my love, FIFA. I promise to take you traveling more, and I apologize for any incomplete or missing events on this website. I hope you love this one.",
    slideImage: "/MINE/naa.jpg",
    shouldDrawLine: true,
    alignment: Branch.LEFT,
  },
];

export type TimelineNodeV2 = CheckpointNode | BranchNode;

export interface CheckpointNode {
  type: NodeTypes.CHECKPOINT;
  title: string;
  subtitle?: string;
  size: ItemSize;
  image?: string;
  slideImage?: string;
  shouldDrawLine: boolean;
  alignment: Branch;
}

export interface BranchNode {
  type: NodeTypes.CONVERGE | NodeTypes.DIVERGE;
}

export const GTAG = "UA-163844688-1";
